# EPG
EPG_URL = 'https://rp-ott-mediation-tv.woopic.com/api-gw/live/v3/applications/STB4PC/programs'
EPG_USER_AGENT = "Opera/9.80 (Linux i686; U; fr) Presto/2.10.287 Version/12.00 ; SC/IHD92 STB"

# channels
CHANNELS = [
    {"index": "0",   "epg_id": "-1",   "name": "GUIDE TV"},
    {"index": "1",   "epg_id": "192",  "name": "TF1"},
    {"index": "2",   "epg_id": "4",    "name": "FRANCE 2"},
    {"index": "3",   "epg_id": "80",   "name": "FRANCE 3"},
    {"index": "4",   "epg_id": "78",   "name": "FRANCE 4"},
    {"index": "5",   "epg_id": "47",   "name": "FRANCE 5"},
    {"index": "6",   "epg_id": "118",  "name": "M6"},
    {"index": "7",   "epg_id": "111",  "name": "ARTE"},
    {"index": "8",   "epg_id": "234",  "name": "LCP/PS"},
    {"index": "9",   "epg_id": "119",  "name": "W9"},
    {"index": "10",  "epg_id": "195",  "name": "TMC"},
    {"index": "11",  "epg_id": "446",  "name": "TFX"},
    {"index": "12",  "epg_id": "482",  "name": "GULLI"},
    {"index": "13",  "epg_id": "481",  "name": "BFM TV"},
    {"index": "14",  "epg_id": "226",  "name": "CNEWS"},
    {"index": "15",  "epg_id": "112",  "name": "LCI"},
    {"index": "16",  "epg_id": "2111", "name": "FRANCEINFO:"},
    {"index": "17",  "epg_id": "458",  "name": "CSTAR"},
    {"index": "18",  "epg_id": "4139",  "name": "T18"},
    {"index": "19",  "epg_id": "160",  "name": "NOVO19"},
    {"index": "20",  "epg_id": "1404", "name": "TF1 SERIES FILMS"},
    {"index": "21",  "epg_id": "1401", "name": "LA CHAINE L'EQUIPE"},
    {"index": "22",  "epg_id": "1403", "name": "6TER"},
    {"index": "23",  "epg_id": "1402", "name": "RMC STORY"},
    {"index": "24",  "epg_id": "1400", "name": "RMC DECOUVERTE"},
    {"index": "25",  "epg_id": "1399", "name": "CHERIE 25"},
    
    {"index": "28",  "epg_id": "-1", "name": "L'ACTU DE LA TV D'ORANGE"},
    {"index": "29",  "epg_id": "-1", "name": "THEMATIQUE DE LA TV D'ORANGE"},
    {"index": "30",  "epg_id": "-1", "name": "MOSAIQUE DES CHAINES LOCALES"},

    {"index": "32",  "epg_id": "-1", "name": "JEUX VIDEOS"},
    {"index": "33",  "epg_id": "205",  "name": "TV5MONDE"},
    {"index": "34",  "epg_id": "115",  "name": "RTL9"},
    {"index": "35",  "epg_id": "191",  "name": "TEVA"},
    {"index": "36",  "epg_id": "145",  "name": "PARIS PREMIERE"},
    {"index": "37",  "epg_id": "225",  "name": "TV BREIZH"},

    {"index": "40",  "epg_id": "34",   "name": "CANAL+"},
    #{"index": "41",  "epg_id": "-1",   "name": "APPLICATION CANAL+"},
    {"index": "42",  "epg_id": "3504", "name": "C+ SPORT360"},
    {"index": "43",  "epg_id": "3501", "name": "C+ FOOT"},
    {"index": "44",  "epg_id": "35", "name": "C+ SPORT"},
    {"index": "45",  "epg_id": "3779", "name": "C+ BOX OFFICE"},
    {"index": "46",  "epg_id": "3349", "name": "C+ GRAND ECRAN"},
    {"index": "47",  "epg_id": "33", "name": "C+ CINEMAS"},
    {"index": "48",  "epg_id": "3347", "name": "C+ DOCS"},
    {"index": "49",  "epg_id": "3348", "name": "C+ KIDS"},
    {"index": "50",  "epg_id": "1290", "name": "BEIN SPORTS 1"},
    {"index": "51",  "epg_id": "1304", "name": "BEIN SPORTS 2"},
    {"index": "52",  "epg_id": "1335", "name": "BEIN SPORTS 3"},
    {"index": "53",  "epg_id": "-1", "name": "DAZN"},
    {"index": "54",  "epg_id": "282", "name": "OCS PREMIER"},
    {"index": "55",  "epg_id": "284", "name": "CINE+ FRISSON"},
    {"index": "56",  "epg_id": "283", "name": "CINE+ EMOTION"},
    {"index": "57",  "epg_id": "401", "name": "CINE+ FAMIZ"},
    {"index": "58",  "epg_id": "285", "name": "CINE+ FESTIVAL"},
    {"index": "59",  "epg_id": "287", "name": "CINE+ CLASSIC"},
    {"index": "60",  "epg_id": "-1", "name": "CINE+ OCS A LA DEMANDE"},
    {"index": "61",  "epg_id": "1562", "name": "PARAMOUNT CHANNEL"},
    {"index": "62",  "epg_id": "2072", "name": "PARAMOUNT CHANNEL DECALE"},
    {"index": "63",  "epg_id": "185", "name": "TCM CINEMA"},
    {"index": "64",  "epg_id": "10", "name": "ACTION"},
    {"index": "65",  "epg_id": "1190", "name": "EUROCHANNEL"},
    # {"index": "66",  "epg_id": "-1", "name": "NETFLIX"},
    # {"index": "67",  "epg_id": "-1", "name": "PRIME VIDEO"},
    # {"index": "68",  "epg_id": "-1", "name": "DISNEY+"},
    # {"index": "69",  "epg_id": "-1", "name": "PARAMOUNT+"},
    # {"index": "70",  "epg_id": "-1", "name": "MAX"},
    # {"index": "71",  "epg_id": "-1", "name": "APPLE TV+"},
    # {"index": "72",  "epg_id": "-1", "name": "CANAL+ SERIES"},
    # {"index": "73",  "epg_id": "-1", "name": "FILMO"},

    {"index": "75",  "epg_id": "405", "name": "E!"},
    {"index": "76",  "epg_id": "128", "name": "MTV"},
    {"index": "77",  "epg_id": "1960", "name": "BET"},
    {"index": "78",  "epg_id": "2334", "name": "WARNER TV"},
    {"index": "79",  "epg_id": "1374", "name": "TLC"},
    {"index": "80",  "epg_id": "5", "name": "AB1"},
    {"index": "81",  "epg_id": "2752", "name": "COMEDY CENTRAL"},
    {"index": "82",  "epg_id": "87", "name": "GAME ONE"},
    {"index": "83",  "epg_id": "1167", "name": "GAME ONE +1"},
    {"index": "84",  "epg_id": "2", "name": "13EME RUE"},
    {"index": "85",  "epg_id": "479", "name": "SYFY"},
    {"index": "86",  "epg_id": "54", "name": "COMEDIE+"},
    {"index": "87",  "epg_id": "2326", "name": "POLAR+"},
    {"index": "88",  "epg_id": "49", "name": "SERIE CLUB"},
    {"index": "89",  "epg_id": "-1", "name": "INA MADELEN"},
    {"index": "90",  "epg_id": "58", "name": "DISNEY CHANNEL"},
    {"index": "91",  "epg_id": "2803", "name": "PITCHOUN TV"},
    # {"index": "92",  "epg_id": "-1", "name": "GULLI MAX"},
    # {"index": "93",  "epg_id": "-1", "name": "TFOU MAX"},
    {"index": "94",  "epg_id": "321", "name": "BOOMERANG"},
    {"index": "95",  "epg_id": "928", "name": "BOOMERANG +1"},
    {"index": "96",  "epg_id": "3738", "name": "CARTOONITOON"},
    {"index": "97",  "epg_id": "229", "name": "TIJI"},
    {"index": "98",  "epg_id": "32", "name": "CANAL J"},
    {"index": "99",  "epg_id": "888", "name": "NICKELODEON JUNIOR"},
    {"index": "100",  "epg_id": "473", "name": "NICKELODEON"},
    {"index": "101",  "epg_id": "2065", "name": "NICKELODEON +1"},
    {"index": "102",  "epg_id": "1746", "name": "NICKELODEON TEEN"},
    {"index": "103",  "epg_id": "3597", "name": "DREAMWORKS"},
    {"index": "105",  "epg_id": "344", "name": "PIWI+"},
    {"index": "106",  "epg_id": "197", "name": "TELETOON+"},
    {"index": "107",  "epg_id": "293", "name": "TELETOON+1"},

    # {"index": "109",  "epg_id": "-1", "name": "PASS VIDEO THEMATIQUE"},
    {"index": "110",  "epg_id": "508", "name": "NATIONAL GEOGRAPHIC"},
    {"index": "111",  "epg_id": "3561", "name": "L'ESPRIT SORCIER"},
    {"index": "112",  "epg_id": "1072", "name": "MUSEUM TV"},
    {"index": "113",  "epg_id": "3360", "name": "MAISONS & TRAVAUX TV"},
    {"index": "114",  "epg_id": "3106", "name": "TOP SANTE TV"},
    {"index": "116",  "epg_id": "2184", "name": "INVESTIGATION DISCOVERY"},
    {"index": "117",  "epg_id": "3155", "name": "MARMITE TV"},
    {"index": "120",  "epg_id": "12", "name": "ANIMAUX"},
    {"index": "121",  "epg_id": "2037", "name": "CRIME DISTRICT"},
    {"index": "122",  "epg_id": "38", "name": "CHASSE & PECHE"},
    {"index": "123",  "epg_id": "7", "name": "TOUTE L'HISTOIRE"},
    {"index": "124",  "epg_id": "88", "name": "HISTOIRE TV"},
    {"index": "125",  "epg_id": "451", "name": "USHUAIA TV"},
    {"index": "126",  "epg_id": "829", "name": "MY ZEN TV"},
    {"index": "127",  "epg_id": "63", "name": "SCIENCE & VIE TV"},
    
    {"index": "132",  "epg_id": "147", "name": "PLANETE+"},
    {"index": "133",  "epg_id": "662", "name": "PLANETE+ CRIME"},
    {"index": "134",  "epg_id": "402", "name": "PLANETE+ AVENTURE"},

    {"index": "139",  "epg_id": "121", "name": "MCM"},
    {"index": "140",  "epg_id": "2353", "name": "MGG TV"},
    {"index": "141",  "epg_id": "2942", "name": "TECH & CO"},
    {"index": "145",  "epg_id": "6", "name": "MANGAS"},
    {"index": "146",  "epg_id": "2040", "name": "WB TV NEXT"},
    {"index": "147",  "epg_id": "1585", "name": "J ONE"},
    # {"index": "148",  "epg_id": "-1", "name": "ADN"},
    {"index": "149",  "epg_id": "4148", "name": "TV PITCHOUN KIDS MUSIC"}, 
    {"index": "150",  "epg_id": "-1", "name": "TRACE URBAN"},
    {"index": "151",  "epg_id": "605", "name": "NRJ HITS"},
    {"index": "152",  "epg_id": "2006", "name": "MTV HITS"},
    {"index": "153",  "epg_id": "2321", "name": "MELODY D'AFRIQUE"},
    {"index": "155",  "epg_id": "1989", "name": "CLUBBING TV"},
    {"index": "157",  "epg_id": "453", "name": "M6MUSIC"},
    {"index": "159",  "epg_id": "241", "name": "RFM"},
    {"index": "160",  "epg_id": "265", "name": "MELODY"},
    {"index": "161",  "epg_id": "753", "name": "TRACE TROPICAL"},
    {"index": "162",  "epg_id": "2744", "name": "TRACE LATINA"},
    {"index": "163",  "epg_id": "2977", "name": "TRACE VANILLA"},
    {"index": "165",  "epg_id": "2462", "name": "CSTAR HITS FRANCE"},
    {"index": "166",  "epg_id": "2958", "name": "OLYMPIA TV"},
    {"index": "167", "epg_id": "125",  "name": "MEZZO"},
    {"index": "168", "epg_id": "907",  "name": "MEZZO LIVE HD"},
    {"index": "169", "epg_id": "1353", "name": "STINGRAY CLASSICA"},
    # {"index": "170",  "epg_id": "-1", "name": "DEEZER"},
    # {"index": "171",  "epg_id": "-1", "name": "ORANGE RADIO"},
    {"index": "172",  "epg_id": "3629", "name": "JOURNAL TV DU GOLF"},
    {"index": "173", "epg_id": "64",   "name": "EQUIDIA"},
    {"index": "174", "epg_id": "2837", "name": "SPORT EN FRANCE"},

    {"index": "179", "epg_id": "1336", "name": "BEIN SPORTS MAX 4"},
    {"index": "180", "epg_id": "1337", "name": "BEIN SPORTS MAX 5"},
    {"index": "181", "epg_id": "1338", "name": "BEIN SPORTS MAX 6"},
    {"index": "182", "epg_id": "1339", "name": "BEIN SPORTS MAX 7"},
    {"index": "183", "epg_id": "1340", "name": "BEIN SPORTS MAX 8"},
    {"index": "184", "epg_id": "1341", "name": "BEIN SPORTS MAX 9"},
    {"index": "185", "epg_id": "1342", "name": "BEIN SPORTS MAX 10"},
    {"index": "196", "epg_id": "15",   "name": "AUTOMOTO LA CHAINE"},

    {"index": "210",  "epg_id": "-1", "name": "ASTRO CENTER"},
    {"index": "211",  "epg_id": "1061", "name": "LUCKY JACK TV"},
    {"index": "213", "epg_id": "1996", "name": "FASHIONTV"},
    {"index": "215", "epg_id": "531",  "name": "LUXE TV"},
    {"index": "216",  "epg_id": "1452", "name": "MEN'S UP TV"},
    {"index": "217",  "epg_id": "3767", "name": "SQOOL TV"},
    {"index": "218",  "epg_id": "-1", "name": "LE FIGARO TV"},
    {"index": "219", "epg_id": "57",   "name": "DEMAIN TV"},
    {"index": "220", "epg_id": "110",  "name": "KTO"},
    {"index": "221",  "epg_id": "-1", "name": "SOUVENIRS FROM EARTH"},

    {"index": "223", "epg_id": "992",  "name": "LCP 100%"},
    {"index": "224",  "epg_id": "2013", "name": "PUBLIC SENAT 24/24"},
    {"index": "225",  "epg_id": "529", "name": "FRANCE 24 FRANCAIS"},
    {"index": "228",  "epg_id": "1073", "name": "BFM BUSINESS"},
    {"index": "229", "epg_id": "140",  "name": "EURONEWS FRANCAIS"},
    {"index": "230",  "epg_id": "-1", "name": "BSMART 4CHANGE"},
    {"index": "231",  "epg_id": "124", "name": "LA CHAINE METEO"},
    {"index": "232", "epg_id": "671",  "name": "FRANCE 24 ENGLISH"},
    {"index": "233",  "epg_id": "2529", "name": "SKY NEWS"},
    {"index": "234", "epg_id": "53",   "name": "CNN"},
    {"index": "235", "epg_id": "51",   "name": "CNBC"},
    {"index": "236", "epg_id": "410",  "name": "BLOOMBERG EUROPE"},
    {"index": "237", "epg_id": "19",   "name": "BBC WORLD NEWS"},
    {"index": "238", "epg_id": "525",  "name": "AL JAZEERA ENGLISH"},
    {"index": "240",  "epg_id": "3413", "name": "FRANCE 24 ARABE"},
    {"index": "241",  "epg_id": "3818", "name": "AL JAZEERA ARABE"},
    {"index": "242", "epg_id": "-1", "name": "MEDI 1 TV"},
    {"index": "243", "epg_id": "781",  "name": "I24NEWS"},
    {"index": "244", "epg_id": "830",  "name": "NHK WORLD - JAPAN"},
    {"index": "245", "epg_id": "61",   "name": "DEUTSCHE WELLE ENGLISH"},
    {"index": "246", "epg_id": "-1",   "name": "TRT WORLD"},
    {"index": "247",  "epg_id": "3562", "name": "FRANCE 24 ESPANOL"},
    {"index": "248",  "epg_id": "3726", "name": "ASHARQ NEWS"},

    # {"index": "270",  "epg_id": "-1", "name": "VOD ADULTE"},
    {"index": "271", "epg_id": "560",  "name": "DORCEL TV"},
    {"index": "272", "epg_id": "1474", "name": "DORCEL XXX"},
    {"index": "273", "epg_id": "218",  "name": "XXL"},
    {"index": "276", "epg_id": "-1",  "name": "UNION TV"},
    {"index": "277", "epg_id": "837",  "name": "PENTHOUSE GOLD"},
    {"index": "278", "epg_id": "1592", "name": "PENTHOUSE QUICKIES"},
    {"index": "279", "epg_id": "1468", "name": "PENTHOUSE BLACK"},
    {"index": "280", "epg_id": "1711", "name": "HUSTLER HD"},
    # {"index": "281", "epg_id": "-1", "name": "MY XXL ILLIMITE"},
    # {"index": "282", "epg_id": "-1", "name": "DORCEL CLUB"},
    {"index": "284", "epg_id": "406",  "name": "PINK X"},
    {"index": "285", "epg_id": "683",  "name": "MAN-X"},
    {"index": "286", "epg_id": "-1", "name": "PINK-X ILLIMITE"},

    # {"index": "297",  "epg_id": "-1", "name": "L'ACTU DE LA TV D'ORANGE"},
    # {"index": "298",  "epg_id": "-1", "name": "THEMATIQUE DE LA TV D'ORANGE"},
    # {"index": "299",  "epg_id": "-1", "name": "MOSAIQUE DES CHAINES LOCALES"},

    {"index": "300", "epg_id": "80",   "name": "FRANCE 3 NATIONALE"},
    {"index": "301", "epg_id": "655",  "name": "FRANCE 3 ALPES"},
    {"index": "302", "epg_id": "249",  "name": "FRANCE 3 ALSACE"},
    {"index": "303", "epg_id": "304",  "name": "FRANCE 3 AQUITAINE"},
    {"index": "304", "epg_id": "649",  "name": "FRANCE 3 AUVERGNE"},
    {"index": "305", "epg_id": "647",  "name": "FRANCE 3 BASSE NORMANDIE"},
    {"index": "306", "epg_id": "636",  "name": "FRANCE 3 BOURGOGNE"},
    {"index": "307", "epg_id": "634",  "name": "FRANCE 3 BRETAGNE"},
    {"index": "308", "epg_id": "306",  "name": "FRANCE 3 CENTRE"},
    {"index": "309", "epg_id": "641",  "name": "FRANCE 3 CHAMPAGNES ARDENNES"},
    {"index": "310", "epg_id": "308",  "name": "FRANCE 3 CORSE"},
    {"index": "311", "epg_id": "642",  "name": "FRANCE 3 CÔTE D'AZUR"},
    {"index": "312", "epg_id": "637",  "name": "FRANCE 3 FRANCHE COMTE"},
    {"index": "313", "epg_id": "646",  "name": "FRANCE 3 HAUTE NORMANDIE"},
    {"index": "314", "epg_id": "650",  "name": "FRANCE 3 LANGUEDOC"},
    {"index": "315", "epg_id": "638",  "name": "FRANCE 3 LIMOUSIN"},
    {"index": "316", "epg_id": "640",  "name": "FRANCE 3 LORRAINE"},
    {"index": "317", "epg_id": "651",  "name": "FRANCE 3 MIDI-PYRENEES"},
    {"index": "318", "epg_id": "644",  "name": "FRANCE 3 NORD PAS DE CALAIS"},
    {"index": "319", "epg_id": "313",  "name": "FRANCE 3 PARIS IDF"},
    {"index": "320", "epg_id": "635",  "name": "FRANCE 3 PAYS DE LA LOIRE"},
    {"index": "321", "epg_id": "645",  "name": "FRANCE 3 PICARDIE"},
    {"index": "322", "epg_id": "639",  "name": "FRANCE 3 POITOU CHARENTES"},
    {"index": "323", "epg_id": "643",  "name": "FRANCE 3 PACA"},
    {"index": "324", "epg_id": "648",  "name": "FRANCE 3 RHONES ALPES"},    

    {"index": "401", "epg_id": "2293", "name": "A+ KIDS"},
    {"index": "403", "epg_id": "185",  "name": "TCM CINEMA VO"},
    {"index": "406",  "epg_id": "1499", "name": "ETV"},
    {"index": "407", "epg_id": "321",  "name": "BOOMERANG (VO)"},
    {"index": "408", "epg_id": "18",   "name": "FOXNEWS"},
    {"index": "409",  "epg_id": "1079", "name": "TELE KREOL"},
    {"index": "410",  "epg_id": "743", "name": "KANAL AUSTRAL"},
    {"index": "412",  "epg_id": "3786", "name": "TV MONACO"},
    {"index": "413",  "epg_id": "2169", "name": "TCM CINEMA ANGLAIS"},
    {"index": "416",  "epg_id": "2168", "name": "BOOMERANG ANGLAIS"},
    {"index": "420", "epg_id": "13",   "name": "RTL NITRO"},
    {"index": "420", "epg_id": "2311", "name": "RTL NITRO"},
    {"index": "422", "epg_id": "219",  "name": "ZDF"},
    {"index": "423", "epg_id": "973",  "name": "ZDF_NEO"},
    {"index": "424", "epg_id": "966",  "name": "RTL 2"},
    {"index": "425", "epg_id": "971",  "name": "VOX"},
    {"index": "427", "epg_id": "964",  "name": "PROSIEBEN"},
    {"index": "428", "epg_id": "1854", "name": "SUPER RTL"},
    {"index": "429", "epg_id": "982",  "name": "KIKA"},
    {"index": "431", "epg_id": "960",  "name": "3SAT"},
    {"index": "432", "epg_id": "979",  "name": "ONE"},
    {"index": "433", "epg_id": "208",  "name": "TVE INTERNACIONAL"},
    {"index": "443", "epg_id": "169",  "name": "RTPI"},
    {"index": "452", "epg_id": "2046", "name": "CANAL Q"},
    {"index": "458",  "epg_id": "1129", "name": "RAI NEWS 24"},   
    {"index": "460", "epg_id": "156",  "name": "RAI UNO"},
    {"index": "461", "epg_id": "154",  "name": "RAI DUE"},
    {"index": "462", "epg_id": "155",  "name": "RAI TRE"},
    {"index": "465",  "epg_id": "791", "name": "RAI ITALIA"},
    {"index": "499", "epg_id": "2000", "name": "THE ISRAELI NETWORK"},
    {"index": "521", "epg_id": "340",  "name": "2M MONDE"},
    {"index": "587",  "epg_id": "1060", "name": "VOX AFRICA"},
    {"index": "599",  "epg_id": "2913", "name": "NCI"},
    {"index": "605",  "epg_id": "1179", "name": "TRACE AFRICA"},
    {"index": "606",  "epg_id": "2022", "name": "TRACE GOSPEL"},
    {"index": "607",  "epg_id": "1832", "name": "NOVELA TV"},
    {"index": "608", "epg_id": "1461", "name": "NOLLYWOOD TV"},
    {"index": "609",  "epg_id": "2908", "name": "SUNU YEUF"},
    {"index": "611", "epg_id": "984",  "name": "EQUINOXE"},
    {"index": "612", "epg_id": "1466", "name": "B-ONE"},

    {"index": "901",  "epg_id": "2527", "name": "TF1 4K"},
    {"index": "902",  "epg_id": "-1", "name": "FRANCE 2 UHD"},
    {"index": "906",  "epg_id": "3301", "name": "M6 4K"}
]
